name: Test

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Test deploy datalake on PR
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id        : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key    : ${{ secrets.AWS_SECRET_KEY }}
        aws-region               : us-east-1

    - name: IAC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        cd infra
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan

  
